apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: psiservices-DevOps-Sheffield
    provider: github
    repository: eas-selt-sqlserver
  name: psiservices-devops-sheffield-eas-selt-sqlserver
spec:
  description: Imported application for psiservices-DevOps-Sheffield/eas-selt-sqlserver
  httpCloneURL: https://github.com/psiservices-DevOps-Sheffield/eas-selt-sqlserver.git
  org: psiservices-DevOps-Sheffield
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: eas-selt-sqlserver
  scheduler:
    kind: ""
    name: ""
  url: git@github.com:psiservices-DevOps-Sheffield/eas-selt-sqlserver.git
