apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  annotations:
    jenkins.io/last-build-number-for-develop: "5"
    jenkins.io/last-build-number-for-master: "1"
    jenkins.io/last-build-number-for-pr-2: "2"
    jenkins.io/last-build-number-for-pr-3: "2"
    jenkins.io/last-build-number-for-pr-4: "5"
  creationTimestamp: null
  labels:
    jenkins.io/chart-release: repos
    jenkins.io/namespace: jx
    jenkins.io/version: "1"
    owner: PSIServices
    provider: github
    repository: eas-selt-results-service
  name: psiservices-eas-selt-results-service
spec:
  description: Imported application for PSIServices/eas-selt-results-service
  httpCloneURL: https://github.com/PSIServices/eas-selt-results-service.git
  org: PSIServices
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: eas-selt-results-service
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/PSIServices/eas-selt-results-service.git
